name: Dependency Vulnerability Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependency-check:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for Node.js project
        id: node_detected
        run: |
          if [ -f "package-lock.json" ]; then
            echo "Node.js project detected."
            echo "is_node=true" >> $GITHUB_ENV
          else
            echo "No Node.js project found."
            echo "is_node=false" >> $GITHUB_ENV

      - name: Running NPM Audit
        if: env.is_node == 'true'
        run: |
          npm install
          npm audit --production --json

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: rohitgitte01/test1
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

          
          

